export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_DATA_START: 'FETCH_CATEGORIES_DATA_START',
    FETCH_CATEGORIES_DATA_SUCCESS: 'FETCH_CATEGORIES_DATA_SUCCESS',
    FETCH_CATEGORIES_DATA_FAILED : 'FETCH_CATEGORIES_DATA_FAILED'
}